<a href="https://colab.research.google.com/github/Shrason/Projects/blob/main/SQL_City_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SQL Murder Mystery**

---



There's been a Murder in SQL City! The SQL Murder Mystery is designed to be both a self-directed lesson to learn SQL concepts and commands and a fun game for experienced SQL users to solve an intriguing crime.
A crime has taken place and the detective needs your help. The detective gave you the crime scene report, but you somehow lost it. You vaguely remember that the crime was a murder that occurred sometime on Jan.15, 2018, and that it took place in SQL City.


In [ ]:
import sqlite3

In [ ]:
connect = sqlite3.connect("/content/sql-murder-mystery.db")
cursor = connect.cursor()

In [ ]:
tablelist = []
for table in cursor.execute("select name from sqlite_master where type = 'table';"):
    tablelist.append(table[0])
tablelist

['crime_scene_report',
 'drivers_license',
 'person',
 'facebook_event_checkin',
 'interview',
 'get_fit_now_member',
 'get_fit_now_check_in',
 'income',
 'solution']

Table info

In [ ]:
cursor.execute("SELECT name, type, sql FROM sqlite_master WHERE type='table'")
table_info = cursor.fetchall()
for name, type, sql in table_info:
    print(name, type, sql)

crime_scene_report table CREATE TABLE crime_scene_report (
        date integer,
        type text,
        description text,
        city text
    )
drivers_license table CREATE TABLE drivers_license (
        id integer PRIMARY KEY,
        age integer,
        height integer,
        eye_color text,
        hair_color text,
        gender text,
        plate_number text,
        car_make text,
        car_model text
    )
person table CREATE TABLE person (
        id integer PRIMARY KEY,
        name text,
        license_id integer,
        address_number integer,
        address_street_name text,
        ssn integer,
        FOREIGN KEY (license_id) REFERENCES drivers_license(id)
    )
facebook_event_checkin table CREATE TABLE facebook_event_checkin (
        person_id integer,
        event_id integer,
        event_name text,
        date integer,
        FOREIGN KEY (person_id) REFERENCES person(id)
    )
interview table CREATE TABLE interview (
        person_id integer,
     

Retrive the crime scene report

In [ ]:
for rows in cursor.execute("SELECT * FROM crime_scene_report LIMIT 10"):
  print(rows)

(20180115, 'robbery', 'A Man Dressed as Spider-Man Is on a Robbery Spree', 'NYC')
(20180115, 'murder', 'Life? Dont talk to me about life.', 'Albany')
(20180115, 'murder', 'Mama, I killed a man, put a gun against his head...', 'Reno')
(20180215, 'murder', 'REDACTED REDACTED REDACTED', 'SQL City')
(20180215, 'murder', 'Someone killed the guard! He took an arrow to the knee!', 'SQL City')
(20180115, 'theft', 'Big Bully stole my lunch money!', 'Chicago')
(20180115, 'fraud', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do\n            eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Seattle')
(20170712, 'theft', 'A lone hunter stalks the night, firing arrows into the Darkness.\n            There is no hiding, no escape. In the distance, the beast\n            falters, tethered to the void. The killing blow comes without\n            hesitation, without mercy.', 'SQL City')
(20170820, 'arson', 'Wield the Hammer of Sol with honor, Titan, it is a thing of\n      

In [ ]:
for rows in cursor.execute("SELECT * FROM crime_scene_report WHERE city = 'SQL City' and type = 'murder'"):
  print(rows)

(20180215, 'murder', 'REDACTED REDACTED REDACTED', 'SQL City')
(20180215, 'murder', 'Someone killed the guard! He took an arrow to the knee!', 'SQL City')
(20180115, 'murder', 'Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".', 'SQL City')


Witness Personal Details

In [ ]:
for rows in cursor.execute("SELECT * FROM person LIMIT 5 "):
  print(rows)

(10000, 'Christoper Peteuil', 993845, 624, 'Bankhall Ave', 747714076)
(10007, 'Kourtney Calderwood', 861794, 2791, 'Gustavus Blvd', 477972044)
(10010, 'Muoi Cary', 385336, 741, 'Northwestern Dr', 828638512)
(10016, 'Era Moselle', 431897, 1987, 'Wood Glade St', 614621061)
(10025, 'Trena Hornby', 550890, 276, 'Daws Hill Way', 223877684)


Witness 1

In [ ]:
for rows in cursor.execute("SELECT *  FROM person WHERE address_street_name = 'Northwestern Dr' ORDER BY address_number DESC LIMIT 5 "):
  print(rows)

(14887, 'Morty Schapiro', 118009, 4919, 'Northwestern Dr', 111564949)
(17729, 'Lasonya Wildey', 439686, 3824, 'Northwestern Dr', 917817122)
(53890, 'Sophie Tiberio', 957671, 3755, 'Northwestern Dr', 442830147)
(73368, 'Torie Thalmann', 773862, 3697, 'Northwestern Dr', 341559436)
(96595, 'Coretta Cubie', 303645, 3631, 'Northwestern Dr', 378403829)


- First witness name is 'Morty Schapiro'

Witness 2

In [ ]:
for rows in cursor.execute("SELECT * FROM person WHERE address_street_name = 'Franklin Ave' and name LIKE 'Annabel' || '%'"):
  print(rows)

(16371, 'Annabel Miller', 490173, 103, 'Franklin Ave', 318771143)


- Second Witness name is 'Annabel Miller'

View Witness Interviews

In [ ]:
for rows in cursor.execute("SELECT * FROM interview WHERE person_id IN (14887,16371)"):
  print(rows)

(14887, 'I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".')
(16371, 'I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.')


- Morty Schaprio heard the gunshot, saw a man running out with a "Get Fit Now Gym" bag having membership number starting from "48Z" which is a gold membership.The man got into a car with a plate that included "H42W"
- Annabel Miller saw the murder and the murder is from her gym. She recognize the killer from her gym while working out last week on January 9th.

Check Gym Database

In [ ]:
for rows in cursor.execute("SELECT * FROM get_fit_now_member WHERE name = 'Annabel Miller'"):
  print(rows)

('90081', 16371, 'Annabel Miller', 20160208, 'gold')


In [ ]:
for rows in cursor.execute("SELECT * FROM get_fit_now_check_in WHERE membership_id = 90081"):
  print(rows)

('90081', 20180109, 1600, 1700)


In [ ]:
for rows in cursor.execute("SELECT * FROM get_fit_now_member WHERE membership_status = 'gold' and id LIKE '48Z%'"):
  print(rows)

('48Z7A', 28819, 'Joe Germuska', 20160305, 'gold')
('48Z55', 67318, 'Jeremy Bowers', 20160101, 'gold')


In [ ]:
for rows in cursor.execute("SELECT * FROM get_fit_now_check_in WHERE membership_id LIKE '48Z%'"):
  print(rows)

('48Z38', 20170611, 813, 1122)
('48Z38', 20171212, 1150, 1153)
('48Z38', 20170820, 919, 921)
('48Z38', 20180314, 315, 1150)
('48Z38', 20170120, 482, 1138)
('48Z7A', 20180109, 1600, 1730)
('48Z55', 20180109, 1530, 1700)


- From the Gym data currently two gold members 'Joe Germuska' and 'Jeremy Bowers' who checked in gym on 9th January at timing near to Annabel Miller i.e 1600 to 1700.

Car Details

In [ ]:
for rows in cursor.execute("SELECT * FROM person WHERE id IN (28819,67318)"):
  print(rows)

(28819, 'Joe Germuska', 173289, 111, 'Fisk Rd', 138909730)
(67318, 'Jeremy Bowers', 423327, 530, 'Washington Pl, Apt 3A', 871539279)


In [ ]:
for rows in cursor.execute("SELECT * FROM drivers_license WHERE id IN (173289,423327)"):
  print(rows)

(423327, 30, 70, 'brown', 'brown', 'male', '0H42W2', 'Chevrolet', 'Spark LS')


- Data for license number 173289 registered on 'Joe Germuska' name was not found from drivers_license table

Personal Details

In [ ]:
for rows in cursor.execute("SELECT * FROM facebook_event_checkin WHERE person_id IN (28819,67318)"):
  print(rows)

(67318, 4719, 'The Funky Grooves Tour', 20180115)
(67318, 1143, 'SQL Symphony Concert', 20171206)


In [ ]:
for rows in cursor.execute("SELECT * FROM income WHERE ssn IN (138909730,871539279)"):
  print(rows)

(871539279, 10500)


- Facebook events data and income information of person_id 28819 i.e Joe Germuska was not found.

Analyze and Draw Conclusions

In [ ]:
for rows in cursor.execute("SELECT * FROM interview WHERE person_id = 67318"):
  print(rows)

(67318, 'I was hired by a woman with a lot of money. I don\'t know her name but I know she\'s around 5\'5" (65") or 5\'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n')


In [ ]:
for rows in cursor.execute("SELECT * FROM drivers_license WHERE car_make = 'Tesla' and gender = 'female' and hair_color = 'red'"):
    print(rows)


(202298, 68, 66, 'green', 'red', 'female', '500123', 'Tesla', 'Model S')
(291182, 65, 66, 'blue', 'red', 'female', '08CM64', 'Tesla', 'Model S')
(918773, 48, 65, 'black', 'red', 'female', '917UU3', 'Tesla', 'Model S')


In [ ]:
for rows in cursor.execute("SELECT * FROM person WHERE license_id IN (202298,291182,918773)"):
  print(rows)

(78881, 'Red Korb', 918773, 107, 'Camerata Dr', 961388910)
(90700, 'Regina George', 291182, 332, 'Maple Ave', 337169072)
(99716, 'Miranda Priestly', 202298, 1883, 'Golden Ave', 987756388)


In [ ]:
for rows in cursor.execute("SELECT * FROM facebook_event_checkin WHERE person_id IN (78881,90700,99716)"):
  print(rows)

(99716, 1143, 'SQL Symphony Concert', 20171206)
(99716, 1143, 'SQL Symphony Concert', 20171212)
(99716, 1143, 'SQL Symphony Concert', 20171229)


- After, the inputs received from Jeremy Bowers's interview were verified, it is found that 'Miranda Priestly' is the mastermind behind the murder that occured in SQL City.

Report

- The details of SQL city murder were retrived from the crime_scene_report. Total three findings were retived,out of which, one stated, the murder occured on  15th January 2018 has two witness.
- With help of personal information table, the two witness were identified. First witness name is 'Morty Schapiro' and Second Witness name is 'Annabel Miller'. After, checking the witness interview it was found that,Morty Schaprio heard the gunshot, saw a man running out with a "Get Fit Now Gym" bag having membership number starting from "48Z" which is a gold membership.The man got into a car with a plate that included "H42W". Annabel Miller saw the murder and the murder is from her gym. She recognize the killer from her gym while working out last week on January 9th.
- With this information and checking the gym table details, two gold members 'Joe Germuska' and 'Jeremy Bowers' checked in gym on 9th January at timing near to Annabel Miller i.e 1600 to 1700. After checking the car details, the car with a plate that included "H42W" is registered under name 'Jeremy Bowers'.
- The personal details of 'Jeremy Bowers'shows that his annual income is 10500, and as per his facebook updates he has join 'The Funky Grooves Tour' on 15th January 2018 and attended 'SQL Symphony Concert' on 6th December 2017.
- Data for license number 173289 registered on 'Joe Germuska' name was not found from drivers_license table, also Facebook events data and income information of person_id 28819 i.e Joe Germuska was not found.
- The interview of Jeremy Bowers stated that, he was hired by a woman who is near about 65"-67" in height, with red hair and drives Tesla Model S. Also, she attended 'SQL Symphony Concert' thrice in December 2017.







- After, the inputs received from Jeremy Bowers's interview were verified, it is found that 'Miranda Priestly' is the mastermind behind the murder that occured in SQL City.

